package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Pcmodules;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PcmodulesMapper {
    List<Pcmodules> selectByRepairId(Integer repairId);
    @Insert("insert into PUBLIC.PC_REPAIR_MODULE (REPAIR_ID, PCMODULE_ID) values (#{repairId}, #{moduleId})")
    int insertPartToJob(@Param("moduleId") Integer moduleId, @Param("repairId") Integer repairId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PCMODULES
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PCMODULES
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    int insert(Pcmodules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PCMODULES
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    Pcmodules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PCMODULES
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    List<Pcmodules> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PCMODULES
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    int updateByPrimaryKey(Pcmodules record);
}