package lt.vu.mybatis.model;

public class Pc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PC.ID
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PC.BRAND
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PC.PCNAME
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    private String pcname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PC.ID
     *
     * @return the value of PUBLIC.PC.ID
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PC.ID
     *
     * @param id the value for PUBLIC.PC.ID
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PC.BRAND
     *
     * @return the value of PUBLIC.PC.BRAND
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PC.BRAND
     *
     * @param brand the value for PUBLIC.PC.BRAND
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PC.PCNAME
     *
     * @return the value of PUBLIC.PC.PCNAME
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public String getPcname() {
        return pcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PC.PCNAME
     *
     * @param pcname the value for PUBLIC.PC.PCNAME
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public void setPcname(String pcname) {
        this.pcname = pcname;
    }
}