package lt.vu.mybatis.model;

import java.util.Objects;

public class Pcmodules {
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Pcmodules)) return false;
        Pcmodules pcmodules = (Pcmodules) o;
        return id.equals(pcmodules.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PCMODULES.ID
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PCMODULES.BRAND
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PCMODULES.NAME
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PCMODULES.PRICE
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PCMODULES.ID
     *
     * @return the value of PUBLIC.PCMODULES.ID
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PCMODULES.ID
     *
     * @param id the value for PUBLIC.PCMODULES.ID
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PCMODULES.BRAND
     *
     * @return the value of PUBLIC.PCMODULES.BRAND
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PCMODULES.BRAND
     *
     * @param brand the value for PUBLIC.PCMODULES.BRAND
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PCMODULES.NAME
     *
     * @return the value of PUBLIC.PCMODULES.NAME
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PCMODULES.NAME
     *
     * @param name the value for PUBLIC.PCMODULES.NAME
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PCMODULES.PRICE
     *
     * @return the value of PUBLIC.PCMODULES.PRICE
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PCMODULES.PRICE
     *
     * @param price the value for PUBLIC.PCMODULES.PRICE
     *
     * @mbg.generated Mon May 03 19:03:24 EEST 2021
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}